version: '3.5'

services:

  postgres:
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    image: postgres
    restart: always
    environment:
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:${POSTGRES_PORT}

  migrate:
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    build:
      context: .
      dockerfile: "dockerfiles/Dockerfile.migrations"
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 5 && python migrate.py'

  insert_to_ping_logger:
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    build:
      context: .
      dockerfile: "dockerfiles/Dockerfile.workers"
    env_file:
      - .env
    depends_on:
      - migrate
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 10 && python consumer.py -q logger.event.insert_ping_logger'

  telegram:
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    build:
      context: .
      dockerfile: "dockerfiles/Dockerfile.workers"
    env_file:
      - .env
    depends_on:
      - migrate
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 10 && python consumer.py -q logger.event.send_message'

  insert_balancing_reports:
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    build:
      context: .
      dockerfile: "dockerfiles/Dockerfile.workers"
    env_file:
      - .env
    depends_on:
      - migrate
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 10 && python consumer.py -q logger.event.insert_balancing_reports'

  insert_deals_reports:
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    build:
      context: .
      dockerfile: "dockerfiles/Dockerfile.workers"
    env_file:
      - .env
    depends_on:
      - migrate
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 10 && python consumer.py -q logger.event.insert_deals_reports'

  insert_balance_check:
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    build:
      context: .
      dockerfile: "dockerfiles/Dockerfile.workers"
    env_file:
      - .env
    depends_on:
      - migrate
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 10 && python consumer.py -q logger.event.insert_balance_check'

  periodic:
    logging:
      driver: 'none'
    build:
      context: .
      dockerfile: "dockerfiles/Dockerfile.workers"
    env_file:
      - .env
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - migrate
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 10 && python periodic.py'
