FROM python:3.9

RUN mkdir start-migrations
WORKDIR /start-migrations/
COPY requirements.txt .
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
COPY /migrations /migrations
COPY migrate.py .
COPY config.py .
ENV PYTHONPATH="/:$PYTHONPATH"